# Generated by Django 4.2.5 on 2023-09-22 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, null=True, verbose_name='title')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='slug')),
                ('location', models.CharField(max_length=50, verbose_name='location')),
                ('city', models.CharField(max_length=128, verbose_name='city')),
                ('type', models.CharField(max_length=128, verbose_name='type')),
                ('surface', models.CharField(max_length=20, verbose_name='surface')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='price')),
                ('description', models.TextField(verbose_name='description')),
                ('currency', models.CharField(choices=[('EUR', 'EUR'), ('CHF', 'CHF')], default='EUR', max_length=3, verbose_name='currency')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='image')),
            ],
            options={
                'verbose_name': 'property',
                'verbose_name_plural': 'properties',
                'db_table': 'properties',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/images', verbose_name='image')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='properties.property', verbose_name='property')),
            ],
            options={
                'verbose_name': 'picture',
                'verbose_name_plural': 'pictures',
                'db_table': 'pictures',
            },
        ),
    ]
