# Generated by Django 4.2.5 on 2023-09-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bedroom',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=4, verbose_name='bedroom'),
        ),
        migrations.AddField(
            model_name='property',
            name='parking',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, verbose_name='parking'),
        ),
    ]
