# Generated by Django 4.2.6 on 2023-10-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='surface',
        ),
        migrations.AddField(
            model_name='property',
            name='construction_surface',
            field=models.CharField(default=0, max_length=20, verbose_name='construction surface'),
        ),
        migrations.AddField(
            model_name='property',
            name='plot_surface',
            field=models.CharField(default=0, max_length=20, verbose_name='plot surface'),
        ),
        migrations.AddField(
            model_name='property',
            name='suite',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='suit'),
        ),
        migrations.AddField(
            model_name='property',
            name='toilet',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=4, verbose_name='toilet'),
        ),
    ]
